#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'serial_msg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 20

# The Active Message type associated with this message.
AM_TYPE = 101

class serial_msg(tinyos.message.Message.Message):
    # Create a new serial_msg of size 20.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=20):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <serial_msg> \n"
        try:
            s += "  [param_one=0x%x]\n" % (self.get_param_one())
        except:
            pass
        try:
            s += "  [param_two=0x%x]\n" % (self.get_param_two())
        except:
            pass
        try:
            s += "  [param_three=0x%x]\n" % (self.get_param_three())
        except:
            pass
        try:
            s += "  [param_four=0x%x]\n" % (self.get_param_four())
        except:
            pass
        try:
            s += "  [param_five=0x%x]\n" % (self.get_param_five())
        except:
            pass
        try:
            s += "  [param_six=0x%x]\n" % (self.get_param_six())
        except:
            pass
        try:
            s += "  [param_seven=0x%x]\n" % (self.get_param_seven())
        except:
            pass
        try:
            s += "  [param_eight=0x%x]\n" % (self.get_param_eight())
        except:
            pass
        try:
            s += "  [param_nine=0x%x]\n" % (self.get_param_nine())
        except:
            pass
        try:
            s += "  [param_ten=0x%x]\n" % (self.get_param_ten())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: param_one
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_one' is signed (False).
    #
    def isSigned_param_one(self):
        return False
    
    #
    # Return whether the field 'param_one' is an array (False).
    #
    def isArray_param_one(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_one'
    #
    def offset_param_one(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_one'
    #
    def offsetBits_param_one(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'param_one'
    #
    def get_param_one(self):
        return self.getUIntElement(self.offsetBits_param_one(), 16, 1)
    
    #
    # Set the value of the field 'param_one'
    #
    def set_param_one(self, value):
        self.setUIntElement(self.offsetBits_param_one(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_one'
    #
    def size_param_one(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_one'
    #
    def sizeBits_param_one(self):
        return 16
    
    #
    # Accessor methods for field: param_two
    #   Field type: int
    #   Offset (bits): 16
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_two' is signed (False).
    #
    def isSigned_param_two(self):
        return False
    
    #
    # Return whether the field 'param_two' is an array (False).
    #
    def isArray_param_two(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_two'
    #
    def offset_param_two(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_two'
    #
    def offsetBits_param_two(self):
        return 16
    
    #
    # Return the value (as a int) of the field 'param_two'
    #
    def get_param_two(self):
        return self.getUIntElement(self.offsetBits_param_two(), 16, 1)
    
    #
    # Set the value of the field 'param_two'
    #
    def set_param_two(self, value):
        self.setUIntElement(self.offsetBits_param_two(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_two'
    #
    def size_param_two(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_two'
    #
    def sizeBits_param_two(self):
        return 16
    
    #
    # Accessor methods for field: param_three
    #   Field type: int
    #   Offset (bits): 32
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_three' is signed (False).
    #
    def isSigned_param_three(self):
        return False
    
    #
    # Return whether the field 'param_three' is an array (False).
    #
    def isArray_param_three(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_three'
    #
    def offset_param_three(self):
        return (32 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_three'
    #
    def offsetBits_param_three(self):
        return 32
    
    #
    # Return the value (as a int) of the field 'param_three'
    #
    def get_param_three(self):
        return self.getUIntElement(self.offsetBits_param_three(), 16, 1)
    
    #
    # Set the value of the field 'param_three'
    #
    def set_param_three(self, value):
        self.setUIntElement(self.offsetBits_param_three(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_three'
    #
    def size_param_three(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_three'
    #
    def sizeBits_param_three(self):
        return 16
    
    #
    # Accessor methods for field: param_four
    #   Field type: int
    #   Offset (bits): 48
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_four' is signed (False).
    #
    def isSigned_param_four(self):
        return False
    
    #
    # Return whether the field 'param_four' is an array (False).
    #
    def isArray_param_four(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_four'
    #
    def offset_param_four(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_four'
    #
    def offsetBits_param_four(self):
        return 48
    
    #
    # Return the value (as a int) of the field 'param_four'
    #
    def get_param_four(self):
        return self.getUIntElement(self.offsetBits_param_four(), 16, 1)
    
    #
    # Set the value of the field 'param_four'
    #
    def set_param_four(self, value):
        self.setUIntElement(self.offsetBits_param_four(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_four'
    #
    def size_param_four(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_four'
    #
    def sizeBits_param_four(self):
        return 16
    
    #
    # Accessor methods for field: param_five
    #   Field type: int
    #   Offset (bits): 64
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_five' is signed (False).
    #
    def isSigned_param_five(self):
        return False
    
    #
    # Return whether the field 'param_five' is an array (False).
    #
    def isArray_param_five(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_five'
    #
    def offset_param_five(self):
        return (64 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_five'
    #
    def offsetBits_param_five(self):
        return 64
    
    #
    # Return the value (as a int) of the field 'param_five'
    #
    def get_param_five(self):
        return self.getUIntElement(self.offsetBits_param_five(), 16, 1)
    
    #
    # Set the value of the field 'param_five'
    #
    def set_param_five(self, value):
        self.setUIntElement(self.offsetBits_param_five(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_five'
    #
    def size_param_five(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_five'
    #
    def sizeBits_param_five(self):
        return 16
    
    #
    # Accessor methods for field: param_six
    #   Field type: int
    #   Offset (bits): 80
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_six' is signed (False).
    #
    def isSigned_param_six(self):
        return False
    
    #
    # Return whether the field 'param_six' is an array (False).
    #
    def isArray_param_six(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_six'
    #
    def offset_param_six(self):
        return (80 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_six'
    #
    def offsetBits_param_six(self):
        return 80
    
    #
    # Return the value (as a int) of the field 'param_six'
    #
    def get_param_six(self):
        return self.getUIntElement(self.offsetBits_param_six(), 16, 1)
    
    #
    # Set the value of the field 'param_six'
    #
    def set_param_six(self, value):
        self.setUIntElement(self.offsetBits_param_six(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_six'
    #
    def size_param_six(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_six'
    #
    def sizeBits_param_six(self):
        return 16
    
    #
    # Accessor methods for field: param_seven
    #   Field type: int
    #   Offset (bits): 96
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_seven' is signed (False).
    #
    def isSigned_param_seven(self):
        return False
    
    #
    # Return whether the field 'param_seven' is an array (False).
    #
    def isArray_param_seven(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_seven'
    #
    def offset_param_seven(self):
        return (96 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_seven'
    #
    def offsetBits_param_seven(self):
        return 96
    
    #
    # Return the value (as a int) of the field 'param_seven'
    #
    def get_param_seven(self):
        return self.getUIntElement(self.offsetBits_param_seven(), 16, 1)
    
    #
    # Set the value of the field 'param_seven'
    #
    def set_param_seven(self, value):
        self.setUIntElement(self.offsetBits_param_seven(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_seven'
    #
    def size_param_seven(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_seven'
    #
    def sizeBits_param_seven(self):
        return 16
    
    #
    # Accessor methods for field: param_eight
    #   Field type: int
    #   Offset (bits): 112
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_eight' is signed (False).
    #
    def isSigned_param_eight(self):
        return False
    
    #
    # Return whether the field 'param_eight' is an array (False).
    #
    def isArray_param_eight(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_eight'
    #
    def offset_param_eight(self):
        return (112 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_eight'
    #
    def offsetBits_param_eight(self):
        return 112
    
    #
    # Return the value (as a int) of the field 'param_eight'
    #
    def get_param_eight(self):
        return self.getUIntElement(self.offsetBits_param_eight(), 16, 1)
    
    #
    # Set the value of the field 'param_eight'
    #
    def set_param_eight(self, value):
        self.setUIntElement(self.offsetBits_param_eight(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_eight'
    #
    def size_param_eight(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_eight'
    #
    def sizeBits_param_eight(self):
        return 16
    
    #
    # Accessor methods for field: param_nine
    #   Field type: int
    #   Offset (bits): 128
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_nine' is signed (False).
    #
    def isSigned_param_nine(self):
        return False
    
    #
    # Return whether the field 'param_nine' is an array (False).
    #
    def isArray_param_nine(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_nine'
    #
    def offset_param_nine(self):
        return (128 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_nine'
    #
    def offsetBits_param_nine(self):
        return 128
    
    #
    # Return the value (as a int) of the field 'param_nine'
    #
    def get_param_nine(self):
        return self.getUIntElement(self.offsetBits_param_nine(), 16, 1)
    
    #
    # Set the value of the field 'param_nine'
    #
    def set_param_nine(self, value):
        self.setUIntElement(self.offsetBits_param_nine(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_nine'
    #
    def size_param_nine(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_nine'
    #
    def sizeBits_param_nine(self):
        return 16
    
    #
    # Accessor methods for field: param_ten
    #   Field type: int
    #   Offset (bits): 144
    #   Size (bits): 16
    #

    #
    # Return whether the field 'param_ten' is signed (False).
    #
    def isSigned_param_ten(self):
        return False
    
    #
    # Return whether the field 'param_ten' is an array (False).
    #
    def isArray_param_ten(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'param_ten'
    #
    def offset_param_ten(self):
        return (144 / 8)
    
    #
    # Return the offset (in bits) of the field 'param_ten'
    #
    def offsetBits_param_ten(self):
        return 144
    
    #
    # Return the value (as a int) of the field 'param_ten'
    #
    def get_param_ten(self):
        return self.getUIntElement(self.offsetBits_param_ten(), 16, 1)
    
    #
    # Set the value of the field 'param_ten'
    #
    def set_param_ten(self, value):
        self.setUIntElement(self.offsetBits_param_ten(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'param_ten'
    #
    def size_param_ten(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'param_ten'
    #
    def sizeBits_param_ten(self):
        return 16
    
