COMPONENT=SerialToRadioAppC



#BUILD_EXTRA_DEPS+=SerialToRadioMsg.py

#SerialToRadioMsg.py: SerialToRadioMsg.h
#	mig python -target=$(PLATFORM) $(CFLAGS) -python-classname=SerialToRadioMsg SerialToRadioMsg.h SerialToRadioMsg -o $@

#CLEAN_EXTRA = SerialToRadioMsg.py


include $(MAKERULES)
